language: go
go:
- 1.6.2
env:
- GOOS=linux GOARCH=amd64
- GOOS=darwin GOARCH=amd64
script:
- go test -v github.com/getblank/blank-sr/sessionstore
- go test -v github.com/getblank/blank-sr/registry
deploy:
  provider: releases
  api-key:
    secure: PYrFuJNn9kiXW2rcuS1koYBuFGfA/v6LeVS4mBoHCow7QW13+MnpgmhBhITuiotXc080bRSEwMPUZhf/o1odJ4odLMlzY2dQU6kfBauUSBUOfgKqDZ6xDcWqhdsdPMdjF+ZVG5u82EMc9Bg9m6tLxJvhbluvBmSr4P8eLyounjbztbu3fMjYjv+bG/0utePk8ZBu0CirHOstpCUK46bOsKJQwdfDiIE8cz34K6+EQeSR7uoNlyyPjZPM33E/CulLoQS266rGfGMh7ZbZYl9/SBTdWBIOb523aOGxT7k93fJnMqau6qBkTJTDfKhso8mI8jQ/vI8xhpifgic/zkEp1nNlMyGBMR31ewWujq5rQpXrFvjZfaF0fJY/bE/qg3X/iuVamjA3AOA3ft7pzDfxNJ99rBxiZp46jSuWUuYnvQRbE18TZYZUZZQwC6/XPtn1yVrn/vnAs57aVlyjmtHtSy8YWJQZiw1hNaxjxm7StQsPXQuLkrCOxlvD6m3Wb+n/2hQS8WRCODsQ3UKlUaoTx79HNFMtqczW9i0Pc3BdBfmKeHkkMxwHeReE39l8fDIOhoWNTy2S0g6jqJ0vQZ84O7sd6+7tVtQKCU03SGiysMPnmQGJDrmPaGj24hURMrD3HeeKiA+KvbMyyec5OgK26XsrODFGvelP/MA5vmlYeUM=
  file: blank-sr
  skip_cleanup: true
  on:
    repo: getblank/blank
    tags: true
    all_branches: true
