language: go

go:
    - 1.6.2
    - tip
env:
    - GOOS=linux GOARCH=amd64
    - GOOS=darwin GOARCH=amd64
script:
    - go test -v github.com/getblank/blank-sr/sessionstore
    - go test -v github.com/getblank/blank-sr/registry