language: go

go:
- 1.6.2

env:
- GOOS=linux GOARCH=amd64
- GOOS=darwin GOARCH=amd64
script:
- go test -v github.com/getblank/blank-sr/sessionstore
- go test -v github.com/getblank/blank-sr/registry
deploy:
  provider: releases
  api-key:
    secure: bFYbTxG2bkAV/Ivqmiy5VK+WR3I+78tpQSAelC0DcvkYwRvdaisdOddDdLo+YRSZFHwPdvdOfUUUHaTIM0uE+axxT9mpFxsjyg0OJhYliFcp3vx2fAcdXTFbnl4ZKfj8AiTSBhhLFfrVpQAFXsubaG4HtZSQynOwqdRNXiBaQmgCLTFsOAibAIBv6GZg3mGSZUnsOkA9vQv4s/YMgVANj3xqXWTIZin4ybyMiQ+WyJrulFrfi/L4XQeD+9E+mch4Di4TFwvNiw4yJqmqYkWxVGojSY1kYOy9JBoI2EB+IbGhB8iDO20ZOtPOqw2s0ta1DMthmSg00tPWs4sLKL/wRCTP16aWk3qAKTDhOwccJKjIfOOMsyFP1Lzrb4WeT5g2fzLgk67VbDb2KHpJg2+WmO9OBcMRb4QwdT20YTwkcKGTMaNNjdl3Bv3gJEuDslO6gYyJ6ZNwqBo4m1cMAVu+ZlBs2tr9fqsMjCp9cmS8DAuHCbKjWkV/77oytMUelmKN6EMVro3Ku+qJdiXM9QlpY/afCIY9TL83hqAAP6TLaujLefOafAyJWBttTKinuCc9eExl/j9ZWjq+rEUivFWfX1y0QSx1m3/5ggDZCTZRUnspBHvAyTZDM2rVQMNrGsNIgUCNZv8o175VgOWsyPeprwMKjgSJNvoVwtqvFCyOfyY=

  file: "blank-sr"
  skip_cleanup: true
  on:
    repo: getblank/Blank
    tags: true
    all_branches: true
